CREATE TABLE IF NOT EXISTS `rider` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '骑手ID',
    `name` varchar(50) NOT NULL COMMENT '骑手姓名',
    `phone` varchar(20) NOT NULL COMMENT '手机号',
    `avatar` varchar(255) DEFAULT NULL COMMENT '头像',
    `id_card` varchar(20) DEFAULT NULL COMMENT '身份证号',
    `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：1-在职，2-离职，3-休息',
    `current_longitude` decimal(10,7) DEFAULT NULL COMMENT '当前经度',
    `current_latitude` decimal(10,7) DEFAULT NULL COMMENT '当前纬度',
    `current_warehouse_id` bigint DEFAULT NULL COMMENT '所属仓库ID',
    `level` int DEFAULT '1' COMMENT '等级',
    `total_orders` int DEFAULT '0' COMMENT '总订单数',
    `rating` decimal(3,2) DEFAULT '5.00' COMMENT '评分',
    `work_status` tinyint NOT NULL DEFAULT '3' COMMENT '工作状态：1-空闲，2-配送中，3-离线',
    `last_online_time` datetime DEFAULT NULL COMMENT '最后在线时间',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_phone` (`phone`),
    KEY `idx_status` (`status`),
    KEY `idx_work_status` (`work_status`),
    KEY `idx_warehouse_id` (`current_warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='骑手表';

CREATE TABLE IF NOT EXISTS `delivery_order` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '配送单ID',
    `delivery_no` varchar(32) NOT NULL COMMENT '配送单号',
    `order_no` varchar(32) NOT NULL COMMENT '主订单号',
    `order_warehouse_id` bigint DEFAULT NULL COMMENT '仓库履约单ID',
    `warehouse_id` bigint NOT NULL COMMENT '仓库ID',
    `rider_id` bigint DEFAULT NULL COMMENT '骑手ID',
    `receiver_name` varchar(50) NOT NULL COMMENT '收货人姓名',
    `receiver_phone` varchar(20) NOT NULL COMMENT '收货人电话',
    `receiver_address` varchar(500) NOT NULL COMMENT '收货地址',
    `longitude` decimal(10,7) NOT NULL COMMENT '经度',
    `latitude` decimal(10,7) NOT NULL COMMENT '纬度',
    `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：1-待接单，2-已接单，3-取货中，4-配送中，5-已完成，6-已取消',
    `delivery_fee` decimal(10,2) DEFAULT '0.00' COMMENT '配送费',
    `distance` decimal(10,2) DEFAULT '0.00' COMMENT '距离（米）',
    `estimate_time` int DEFAULT NULL COMMENT '预计时长（分钟）',
    `pickup_time` datetime DEFAULT NULL COMMENT '取货时间',
    `delivery_time` datetime DEFAULT NULL COMMENT '送达时间',
    `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_delivery_no` (`delivery_no`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_rider_id` (`rider_id`),
    KEY `idx_warehouse_id` (`warehouse_id`),
    KEY `idx_status` (`status`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='配送订单表';

CREATE TABLE IF NOT EXISTS `delivery_track` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '轨迹ID',
    `delivery_id` bigint NOT NULL COMMENT '配送单ID',
    `rider_id` bigint NOT NULL COMMENT '骑手ID',
    `longitude` decimal(10,7) NOT NULL COMMENT '经度',
    `latitude` decimal(10,7) NOT NULL COMMENT '纬度',
    `speed` decimal(5,2) DEFAULT NULL COMMENT '速度（m/s）',
    `direction` varchar(20) DEFAULT NULL COMMENT '方向',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    KEY `idx_delivery_id` (`delivery_id`),
    KEY `idx_rider_id` (`rider_id`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='配送轨迹表';

CREATE TABLE IF NOT EXISTS `dispatch_record` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '调度记录ID',
    `delivery_id` bigint NOT NULL COMMENT '配送单ID',
    `delivery_no` varchar(32) NOT NULL COMMENT '配送单号',
    `rider_id` bigint NOT NULL COMMENT '骑手ID',
    `rider_name` varchar(50) DEFAULT NULL COMMENT '骑手姓名',
    `dispatch_type` tinyint NOT NULL COMMENT '调度类型：1-系统自动派单，2-骑手主动接单，3-后台手动派单，4-转单，5-二次调度',
    `dispatch_reason` varchar(500) DEFAULT NULL COMMENT '调度原因',
    `distance` decimal(10,2) DEFAULT NULL COMMENT '距离（米）',
    `estimate_time` int DEFAULT NULL COMMENT '预计时长（分钟）',
    `dispatch_time` datetime DEFAULT NULL COMMENT '调度时间',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    KEY `idx_delivery_id` (`delivery_id`),
    KEY `idx_rider_id` (`rider_id`),
    KEY `idx_dispatch_type` (`dispatch_type`),
    KEY `idx_dispatch_time` (`dispatch_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='调度记录表';
